// Mocks generated by Mockito 5.4.6 from annotations
// in budget_manage/test/features/salary/domain/usecases/set_monthly_salary_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:budget_manage/features/budget/domain/entities/budget.dart'
    as _i6;
import 'package:budget_manage/features/budget/domain/repositories/budget_repository.dart'
    as _i5;
import 'package:budget_manage/features/expense/domain/entities/expense.dart'
    as _i8;
import 'package:budget_manage/features/expense/domain/repositories/expense_repository.dart'
    as _i7;
import 'package:budget_manage/features/salary/domain/entities/salary.dart'
    as _i4;
import 'package:budget_manage/features/salary/domain/repositories/salary_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SalaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalaryRepository extends _i1.Mock implements _i2.SalaryRepository {
  MockSalaryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Salary?> getSalary(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getSalary, [month, year]),
            returnValue: _i3.Future<_i4.Salary?>.value(),
          )
          as _i3.Future<_i4.Salary?>);

  @override
  _i3.Future<List<_i4.Salary>> getAllSalaries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSalaries, []),
            returnValue: _i3.Future<List<_i4.Salary>>.value(<_i4.Salary>[]),
          )
          as _i3.Future<List<_i4.Salary>>);

  @override
  _i3.Future<void> saveSalary(_i4.Salary? salary) =>
      (super.noSuchMethod(
            Invocation.method(#saveSalary, [salary]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateRemaining(int? month, int? year, double? remaining) =>
      (super.noSuchMethod(
            Invocation.method(#updateRemaining, [month, year, remaining]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSalary(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSalary, [month, year]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BudgetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBudgetRepository extends _i1.Mock implements _i5.BudgetRepository {
  MockBudgetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.Budget>> getBudgets(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgets, [month, year]),
            returnValue: _i3.Future<List<_i6.Budget>>.value(<_i6.Budget>[]),
          )
          as _i3.Future<List<_i6.Budget>>);

  @override
  _i3.Future<List<_i6.Budget>> getAllBudgets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBudgets, []),
            returnValue: _i3.Future<List<_i6.Budget>>.value(<_i6.Budget>[]),
          )
          as _i3.Future<List<_i6.Budget>>);

  @override
  _i3.Future<_i6.Budget?> getBudgetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetById, [id]),
            returnValue: _i3.Future<_i6.Budget?>.value(),
          )
          as _i3.Future<_i6.Budget?>);

  @override
  _i3.Future<void> saveBudget(_i6.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#saveBudget, [budget]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBudget(_i6.Budget? budget) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudget, [budget]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBudget(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllBudgets() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllBudgets, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double> getTotalAllocatedAmount(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalAllocatedAmount, [month, year]),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i7.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i8.Expense>> getExpenses(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenses, [month, year]),
            returnValue: _i3.Future<List<_i8.Expense>>.value(<_i8.Expense>[]),
          )
          as _i3.Future<List<_i8.Expense>>);

  @override
  _i3.Future<List<_i8.Expense>> getExpensesByBudgetId(
    String? budgetId,
    int? month,
    int? year,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByBudgetId, [budgetId, month, year]),
            returnValue: _i3.Future<List<_i8.Expense>>.value(<_i8.Expense>[]),
          )
          as _i3.Future<List<_i8.Expense>>);

  @override
  _i3.Future<List<_i8.Expense>> getAllExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllExpenses, []),
            returnValue: _i3.Future<List<_i8.Expense>>.value(<_i8.Expense>[]),
          )
          as _i3.Future<List<_i8.Expense>>);

  @override
  _i3.Future<void> saveExpense(_i8.Expense? expense) =>
      (super.noSuchMethod(
            Invocation.method(#saveExpense, [expense]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteExpense(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllExpenses, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
